### ISSUE TITLE
Not working with jabref 2.9.2 ?

### ISSUE THREAD

**Issue by arnaud-m** [korv/Jabref-plugins#4]
The plugin is not working with JabRef 2.9.2 : 

```
Sep 19, 2013 11:34:27 AM net.sf.jabref.plugin.PluginCore initialize
INFO: Found 3 plugin(s):
  - net.sf.jabref.core (jar:file:/opt/JabRef-2.9.2.jar!/plugins/net.sf.jabref.core/plugin.xml)
  - renameFile (jar:file:/home/nono/.jabref/plugins/renamefile.1.2.jar!/plugin.xml)
  - net.sf.jabref.export.misq (jar:file:/opt/JabRef-2.9.2.jar!/plugins/net.sf.jabref.export.misq/plugin.xml)

Sep 19, 2013 11:34:28 AM net.sf.jabref.Globals logger
INFO: Opening: /home/nono/research/bibli.bib
```

The Rename Dialog works just fine, but do not succeed to effectively rename files.
It raises the following java exception:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: net.sf.jabref.MetaData.getFileDirectory(Ljava/lang/String;)Ljava/lang/String;
    at renamefile.Utils.getFileDir(Utils.java:79)
    at renamefile.RenameDialog.renameFile(RenameDialog.java:266)
    at renamefile.RenameDialog.actionPerformed(RenameDialog.java:234)

```

Thank you for your time.
